---
name: Stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: ivuorinen/actions/stale@c571c2bb13e37440cf51fe49ca55b025f5c3da77 # v2026.04.05
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
