---
name: Stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write # only for delete-branch option
  issues: write
  pull-requests: write

jobs:
  stale:
    uses: ivuorinen/ivuorinen/.github/workflows/stale.yml@12541aa4ea9228f2e118f879a66a4a7b402e8ef1 # main
